//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookForConsumingWCF.WCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/BookWcfService")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Get", ReplyAction="http://tempuri.org/IBookService/GetResponse")]
        BookForConsumingWCF.WCFServiceReference.Contact[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Get", ReplyAction="http://tempuri.org/IBookService/GetResponse")]
        System.Threading.Tasks.Task<BookForConsumingWCF.WCFServiceReference.Contact[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Insert", ReplyAction="http://tempuri.org/IBookService/InsertResponse")]
        void Insert(BookForConsumingWCF.WCFServiceReference.Contact cobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Insert", ReplyAction="http://tempuri.org/IBookService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(BookForConsumingWCF.WCFServiceReference.Contact cobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Update", ReplyAction="http://tempuri.org/IBookService/UpdateResponse")]
        void Update(BookForConsumingWCF.WCFServiceReference.Contact cobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Update", ReplyAction="http://tempuri.org/IBookService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(BookForConsumingWCF.WCFServiceReference.Contact cobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Delete", ReplyAction="http://tempuri.org/IBookService/DeleteResponse")]
        void Delete(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Delete", ReplyAction="http://tempuri.org/IBookService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : BookForConsumingWCF.WCFServiceReference.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<BookForConsumingWCF.WCFServiceReference.IBookService>, BookForConsumingWCF.WCFServiceReference.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookForConsumingWCF.WCFServiceReference.Contact[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<BookForConsumingWCF.WCFServiceReference.Contact[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public void Insert(BookForConsumingWCF.WCFServiceReference.Contact cobj) {
            base.Channel.Insert(cobj);
        }
        
        public System.Threading.Tasks.Task InsertAsync(BookForConsumingWCF.WCFServiceReference.Contact cobj) {
            return base.Channel.InsertAsync(cobj);
        }
        
        public void Update(BookForConsumingWCF.WCFServiceReference.Contact cobj) {
            base.Channel.Update(cobj);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(BookForConsumingWCF.WCFServiceReference.Contact cobj) {
            return base.Channel.UpdateAsync(cobj);
        }
        
        public void Delete(int Id) {
            base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int Id) {
            return base.Channel.DeleteAsync(Id);
        }
    }
}
